name: dart_task
description: Application CLI de gestion de taches en Dart avec persistance JSON.
version: 1.0.0
repository: https://github.com/borisgnanzim/dart_task

environment:
  sdk: ^3.7.2

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
